// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// model_3pl_prob
NumericMatrix model_3pl_prob(NumericVector t, NumericVector a, NumericVector b, NumericVector c, double D);
RcppExport SEXP _Rirt_model_3pl_prob(SEXP tSEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(model_3pl_prob(t, a, b, c, D));
    return rcpp_result_gen;
END_RCPP
}
// model_3pl_info
NumericMatrix model_3pl_info(NumericVector t, NumericVector a, NumericVector b, NumericVector c, double D);
RcppExport SEXP _Rirt_model_3pl_info(SEXP tSEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(model_3pl_info(t, a, b, c, D));
    return rcpp_result_gen;
END_RCPP
}
// model_3pl_dvC
List model_3pl_dvC(NumericMatrix u, List quad, NumericVector a, NumericVector b, NumericVector c, double D);
RcppExport SEXP _Rirt_model_3pl_dvC(SEXP uSEXP, SEXP quadSEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< List >::type quad(quadSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(model_3pl_dvC(u, quad, a, b, c, D));
    return rcpp_result_gen;
END_RCPP
}
// model_gpcm_probC
List model_gpcm_probC(NumericVector t, NumericVector a, NumericVector b, NumericMatrix d, double D);
RcppExport SEXP _Rirt_model_gpcm_probC(SEXP tSEXP, SEXP aSEXP, SEXP bSEXP, SEXP dSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(model_gpcm_probC(t, a, b, d, D));
    return rcpp_result_gen;
END_RCPP
}
// model_grm_prob_rawC
List model_grm_prob_rawC(NumericVector t, NumericVector a, NumericMatrix b, double D);
RcppExport SEXP _Rirt_model_grm_prob_rawC(SEXP tSEXP, SEXP aSEXP, SEXP bSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(model_grm_prob_rawC(t, a, b, D));
    return rcpp_result_gen;
END_RCPP
}
// model_grm_probC
List model_grm_probC(NumericVector t, NumericVector a, NumericMatrix b, double D);
RcppExport SEXP _Rirt_model_grm_probC(SEXP tSEXP, SEXP aSEXP, SEXP bSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(model_grm_probC(t, a, b, D));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rirt_model_3pl_prob", (DL_FUNC) &_Rirt_model_3pl_prob, 5},
    {"_Rirt_model_3pl_info", (DL_FUNC) &_Rirt_model_3pl_info, 5},
    {"_Rirt_model_3pl_dvC", (DL_FUNC) &_Rirt_model_3pl_dvC, 6},
    {"_Rirt_model_gpcm_probC", (DL_FUNC) &_Rirt_model_gpcm_probC, 5},
    {"_Rirt_model_grm_prob_rawC", (DL_FUNC) &_Rirt_model_grm_prob_rawC, 4},
    {"_Rirt_model_grm_probC", (DL_FUNC) &_Rirt_model_grm_probC, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rirt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
