# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname model_3pl
#' @param t ability parameters, 1d vector
#' @param a discrimination parameters, 1d vector
#' @param b difficulty parameters, 1d vector
#' @param c guessing parameters, 1d vector
#' @param D the scaling constant, default=1.702
#' @return \code{model_3pl_prob} returns the resulting probabilities in a matrix
#' @examples
#' with(model_3pl_gendata(10, 5), model_3pl_prob(t, a, b, c))
#' @export
model_3pl_prob <- function(t, a, b, c, D = 1.702) {
    .Call('_Rirt_model_3pl_prob', PACKAGE = 'Rirt', t, a, b, c, D)
}

#' @rdname model_3pl
#' @return \code{model_3pl_info} returns the resulting information in a matrix
#' @examples
#' with(model_3pl_gendata(10, 5), model_3pl_info(t, a, b, c))
#' @export
model_3pl_info <- function(t, a, b, c, D = 1.702) {
    .Call('_Rirt_model_3pl_info', PACKAGE = 'Rirt', t, a, b, c, D)
}

model_3pl_dvC <- function(u, quad, a, b, c, D = 1.702) {
    .Call('_Rirt_model_3pl_dvC', PACKAGE = 'Rirt', u, quad, a, b, c, D)
}

model_gpcm_probC <- function(t, a, b, d, D = 1.702) {
    .Call('_Rirt_model_gpcm_probC', PACKAGE = 'Rirt', t, a, b, d, D)
}

model_grm_prob_rawC <- function(t, a, b, D = 1.702) {
    .Call('_Rirt_model_grm_prob_rawC', PACKAGE = 'Rirt', t, a, b, D)
}

model_grm_probC <- function(t, a, b, D = 1.702) {
    .Call('_Rirt_model_grm_probC', PACKAGE = 'Rirt', t, a, b, D)
}

